package com.alpha.dao;

import com.alpha.entity.Backlog;
import java.util.List;

public interface BacklogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backlog
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backlog
     *
     * @mbggenerated
     */
    int insert(Backlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backlog
     *
     * @mbggenerated
     */
    Backlog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backlog
     *
     * @mbggenerated
     */
    List<Backlog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backlog
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Backlog record);

    List<Backlog> getAllByUserId(Integer userId);
}