package com.alpha.entity;

public class Address {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.street
     *
     * @mbggenerated
     */
    private String street;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.number
     *
     * @mbggenerated
     */
    private Integer number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.backlogId
     *
     * @mbggenerated
     */
    private Integer backlogid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.id
     *
     * @return the value of address.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.id
     *
     * @param id the value for address.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.street
     *
     * @return the value of address.street
     *
     * @mbggenerated
     */
    public String getStreet() {
        return street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.street
     *
     * @param street the value for address.street
     *
     * @mbggenerated
     */
    public void setStreet(String street) {
        this.street = street == null ? null : street.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.number
     *
     * @return the value of address.number
     *
     * @mbggenerated
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.number
     *
     * @param number the value for address.number
     *
     * @mbggenerated
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.backlogId
     *
     * @return the value of address.backlogId
     *
     * @mbggenerated
     */
    public Integer getBacklogid() {
        return backlogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.backlogId
     *
     * @param backlogid the value for address.backlogId
     *
     * @mbggenerated
     */
    public void setBacklogid(Integer backlogid) {
        this.backlogid = backlogid;
    }
}