package com.alpha.dao;

import com.alpha.entity.Backlog;
import com.alpha.entity.Cooperator;
import java.util.List;

public interface CooperatorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cooperator
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cooperator
     *
     * @mbggenerated
     */
    int insert(Cooperator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cooperator
     *
     * @mbggenerated
     */
    Cooperator selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cooperator
     *
     * @mbggenerated
     */
    List<Cooperator> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cooperator
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Cooperator record);

    List<Backlog> getCooperatorsByBacklogId(Integer backlogId);
}