package com.alpha.entity;

public class Cooperator {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cooperator.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cooperator.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cooperator.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cooperator.backlogId
     *
     * @mbggenerated
     */
    private Integer backlogid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cooperator.id
     *
     * @return the value of cooperator.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cooperator.id
     *
     * @param id the value for cooperator.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cooperator.name
     *
     * @return the value of cooperator.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cooperator.name
     *
     * @param name the value for cooperator.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cooperator.email
     *
     * @return the value of cooperator.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cooperator.email
     *
     * @param email the value for cooperator.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cooperator.backlogId
     *
     * @return the value of cooperator.backlogId
     *
     * @mbggenerated
     */
    public Integer getBacklogid() {
        return backlogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cooperator.backlogId
     *
     * @param backlogid the value for cooperator.backlogId
     *
     * @mbggenerated
     */
    public void setBacklogid(Integer backlogid) {
        this.backlogid = backlogid;
    }
}